/* @generated by scripts/generate-routes.ts — do not edit */
export type Href =
  | "/"
  | `/api/auth/${string}`
  | "/auth"
  | "/dashboard"
  | "/learn"
  | "/lessons/greetings"
  | "/review/session"
  | "/settings"
  | "/watch";
