#!/usr/bin/env node
// Makes the Expo Router routes (and the @nn/router Href union) from the web
// TanStack routes — the web route tree is the source of truth. Reads
// routeTree.gen.ts with a regex: do not import it, it pulls in every route
// component. Each stub mirrors the web route's own @nn/features import, so
// the generator assumes no path convention inside @nn/features.
import * as fs from "node:fs";
import * as path from "node:path";

const repoRoot = path.resolve(import.meta.dirname, "..");
const routeTreePath = path.join(repoRoot, "apps/tanstack-start/src/routeTree.gen.ts");
const webRoutesDir = path.join(repoRoot, "apps/tanstack-start/src/routes");
const appDir = path.join(repoRoot, "apps/expo/src/app");

const GENERATED_MARKER = "@" + "generated by scripts/generate-routes.ts";
// Match only the page (default) import — routes may also import named helpers.
const PAGE_IMPORT_RE =
  /import\s+[A-Za-z_$][\w$]*\s*(?:,\s*\{[^}]*\})?\s*from\s+["'](@nn\/features\/[^"']+)["']/u;

function fail(msg: string): never {
  console.error(`\n[generate-routes] ERROR: ${msg}\n`);
  process.exit(1);
}

if (!fs.existsSync(routeTreePath)) {
  fail(
    `${path.relative(repoRoot, routeTreePath)} not found.\n` +
      `Run the web app once first (nub run dev:tanstack-start or nub run -F @nn/tanstack-start build) so ` +
      `TanStack Router generates it.`,
  );
}

// FileRoutesByFullPath holds full URLs (`/cheatsheets`, not
// `/_home/cheatsheets`). This script does not need to handle layout syntax.
const blockMatch = fs
  .readFileSync(routeTreePath, "utf8")
  .match(/interface FileRoutesByFullPath\s*\{([\s\S]*?)\n\}/u);
const block = blockMatch?.[1];
if (block === undefined) {
  fail(
    "Could not find `interface FileRoutesByFullPath` in routeTree.gen.ts. " +
      "TanStack Router's generated format may have changed — update this parser.",
  );
}

const keyRegex = /^\s*['"]([^'"]+)['"]\s*:/gmu;
const paths = new Set<string>();
for (const match of block.matchAll(keyRegex)) {
  let p = match[1];
  if (p === undefined) continue;
  if (p.length > 1 && p.endsWith("/")) p = p.slice(0, -1);
  paths.add(p);
}

if (paths.size === 0) {
  fail(
    "Parsed zero routes out of FileRoutesByFullPath. " +
      "TanStack Router's generated format may have changed — update this parser.",
  );
}

/** `/lessons/$slug` -> web route file `lessons.$slug.tsx` */
function toWebRouteModule(routePath: string): string {
  return routePath === "/" ? "index" : routePath.slice(1).replaceAll("/", ".");
}
/** `/lessons/$slug` -> mobile file `lessons/[slug].tsx` */
function toNativeFile(routePath: string): string {
  const rel =
    routePath === "/"
      ? "index"
      : routePath
          .slice(1)
          .split("/")
          .map((seg) => (seg.startsWith("$") ? `[${seg.slice(1)}]` : seg))
          .join("/");
  return `${rel}.tsx`;
}

const problems: string[] = [];
const emitted = new Set<string>();
const layoutPaths = new Set<string>();

for (const routePath of [...paths].sort((a, b) => a.localeCompare(b))) {
  // Server-only routes (auth proxy, image endpoints) have no mobile page.
  if (routePath.startsWith("/api/")) continue;
  const webFile = path.join(webRoutesDir, `${toWebRouteModule(routePath)}.tsx`);
  if (!fs.existsSync(webFile)) {
    problems.push(`${routePath}: no web route file at ${path.relative(repoRoot, webFile)}`);
    continue;
  }
  const contents = fs.readFileSync(webFile, "utf8");
  // A route that renders an Outlet is a layout. Mobile layouts are written by
  // hand (_layout.tsx files), so emit no stub and no Href entry for it.
  if (contents.includes("<Outlet")) {
    layoutPaths.add(routePath);
    continue;
  }
  const src = contents.match(PAGE_IMPORT_RE)?.[1];
  if (src === undefined) {
    problems.push(
      `${routePath}: ${path.relative(repoRoot, webFile)} has no @nn/features page import`,
    );
    continue;
  }

  const outFile = path.join(appDir, toNativeFile(routePath));
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(
    outFile,
    `/* ${GENERATED_MARKER} — do not edit */\n` + `export { default } from "${src}";\n`,
  );
  emitted.add(outFile);
}

if (problems.length > 0) {
  fail(`Every web route needs an @nn/features page import:\n  ${problems.join("\n  ")}`);
}

// Remove old generated files for routes that no longer exist.
// Keep files written by hand. They do not have the generated marker.
function sweep(dir: string): void {
  if (!fs.existsSync(dir)) return;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      sweep(full);
      if (fs.readdirSync(full).length === 0) fs.rmdirSync(full);
    } else if (
      full.endsWith(".tsx") &&
      !emitted.has(full) &&
      fs.readFileSync(full, "utf8").includes(GENERATED_MARKER)
    ) {
      fs.unlinkSync(full);
      console.log(`  removed stale ${path.relative(repoRoot, full)}`);
    }
  }
}
sweep(appDir);

// Emit the shared Href type for @nn/router from the same route list.
// A static route becomes a string literal ("/watch"); a $param segment becomes
// ${string} so a resolved path (`/lessons/abc`) type-checks against it.
const hrefMembers = [...paths]
  .filter((p) => !layoutPaths.has(p))
  .sort((a, b) => a.localeCompare(b))
  .map((p) => {
    if (!p.includes("$")) return JSON.stringify(p);
    const tpl = p
      .split("/")
      .map((seg) => (seg.startsWith("$") ? "${string}" : seg))
      .join("/");
    return `\`${tpl}\``;
  });
fs.writeFileSync(
  path.join(repoRoot, "packages/router/src/routes.gen.ts"),
  `/* ${GENERATED_MARKER} — do not edit */\n` +
    `export type Href =\n  | ${hrefMembers.join("\n  | ")};\n`,
);

console.log(`[generate-routes] ${emitted.size} routes generated from ${paths.size} web routes.`);
